#  Handling Imbalanced Dataset with ML 

In [56]:
pip install imbalanced-learn

Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd 
df = pd.read_csv('https://raw.githubusercontent.com/nsethi31/Kaggle-Data-Credit-Card-Fraud-Detection/master/creditcard.csv')

In [5]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [6]:
df.shape

(284807, 31)

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
df['Class'].value_counts()   #####Use Diffferen in both 0 and 1 Not balanced 

0    284315
1       492
Name: Class, dtype: int64

In [10]:
### Independent and Dependent Features 
X = df.drop("Class",axis=1)
y=df.Class

## Cross validatioan like  KFOLD and Hyperparmeter Turning

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np 
from sklearn.model_selection import GridSearchCV

In [14]:
10.0**np.arange(-2,3)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [15]:
log_class = LogisticRegression()
grid= {'C':10.0**np.arange(-2,3),'penalty':['l1','l2']}
cv= KFold(n_splits=5,shuffle=False,random_state=None)

In [19]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7)

In [20]:
clf = GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

C:\tools\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\tools\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\tools\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\tools\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 447, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs sup

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [21]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85274    33]
 [   51    85]]
0.9990168884519505
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.72      0.62      0.67       136

    accuracy                           1.00     85443
   macro avg       0.86      0.81      0.83     85443
weighted avg       1.00      1.00      1.00     85443



In [29]:
X_train.shape

(199364, 30)

In [31]:
y_train.value_counts()

0    199008
1       356
Name: Class, dtype: int64

In [33]:
class_weight =  dict({0:1,1:100}) #give the importance to 1 

In [34]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight = class_weight)
classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [25]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85304     3]
 [   32   104]]
0.9995903701883126
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85307
           1       0.97      0.76      0.86       136

    accuracy                           1.00     85443
   macro avg       0.99      0.88      0.93     85443
weighted avg       1.00      1.00      1.00     85443



###### Under Sampling  ----reduce the points of the maximum labels ---Never do if data is small

In [39]:
from collections import Counter
Counter(y_train)

Counter({0: 199008, 1: 356})

In [60]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)

X_train_ns,y_train_ns=ns.fit_sample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

AttributeError: 'NearMiss' object has no attribute 'fit_sample'

In [70]:
from imblearn.under_sampling import RandomUnderSampler  

under_sampler = RandomUnderSampler(0.8)
X_train_ns,y_train_ns=under_sampler.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199008, 1: 356})
The number of classes after fit Counter({0: 445, 1: 356})


C:\tools\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [71]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight = class_weight)
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [72]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[84371   936]
 [   23   113]]
0.9887761431597674
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     85307
           1       0.11      0.83      0.19       136

    accuracy                           0.99     85443
   macro avg       0.55      0.91      0.59     85443
weighted avg       1.00      0.99      0.99     85443



### Over Sampling 


In [82]:
from imblearn.over_sampling import RandomOverSampler
over_sampler = RandomUnderSampler(0.5)
X_train_ns,y_train_ns=over_sampler.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199008, 1: 356})
The number of classes after fit Counter({0: 712, 1: 356})


C:\tools\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [83]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight = class_weight)
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [84]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[84833   474]
 [   23   113]]
0.99418325667404
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     85307
           1       0.19      0.83      0.31       136

    accuracy                           0.99     85443
   macro avg       0.60      0.91      0.65     85443
weighted avg       1.00      0.99      1.00     85443

